name: 'FTP Deploy'
description: 'Deploy files to FTP server'
inputs:
  server:
    description: 'FTP server address'
    required: true
  port:
    description: 'FTP server port'
    required: true
  protocol:
    description: 'FTP protocol (ftp or ftps)'
    required: true
  username:
    description: 'FTP username'
    required: true
  password:
    description: 'FTP password'
    required: true
  local-dir:
    description: 'Local directory to deploy'
    required: true
  server-dir:
    description: 'Remote server directory (optional)'
    required: false
    default: './'
  exclude:
    description: 'Files/directories to exclude (multiline string)'
    required: false
    default: |
      **/.git*
      **/.git*/**
      **/node_modules/**
      **/cgi-bin/**

runs:
  using: 'composite'
  steps:
    - name: 📂 Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.6
      with:
        server: ${{ inputs.server }}
        port: ${{ inputs.port }}
        protocol: ${{ inputs.protocol }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        local-dir: ${{ inputs.local-dir }}
        server-dir: ${{ inputs.server-dir }}
        exclude: ${{ inputs.exclude }}
