name: 'Install Playwright'
description: 'Install Playwright browsers with chromium'
inputs:
  browsers:
    description: 'Browsers to install (e.g., chromium, firefox, webkit)'
    required: false
    default: 'chromium'
  with-deps:
    description: 'Install system dependencies'
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Cache Playwright browsers
      uses: actions/cache@v5
      with:
        path: ~/.cache/ms-playwright
        key: playwright-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}

    - name: Install Playwright browsers
      shell: bash
      run: |
        if [ "${{ inputs.with-deps }}" = "true" ]; then
          pnpm --filter @grasdouble/lufa_design-system-playwright exec playwright install --with-deps ${{ inputs.browsers }}
        else
          pnpm --filter @grasdouble/lufa_design-system-playwright exec playwright install ${{ inputs.browsers }}
        fi
