declare const styles: {
    readonly steps: string;
    readonly step: string;
    readonly clickable: string;
    readonly stepIcon: string;
    readonly stepNumber: string;
    readonly customIcon: string;
    readonly stepContent: string;
    readonly stepTitle: string;
    readonly stepDescription: string;
    readonly stepConnector: string;
    readonly directionHorizontal: string;
    readonly directionVertical: string;
    readonly sizeDefault: string;
    readonly sizeSmall: string;
    readonly statusWait: string;
    readonly statusProcess: string;
    readonly statusFinish: string;
    readonly statusError: string;
};
export default styles;
