declare const styles: {
  readonly flex: string;
  readonly block: string;
  readonly inline: string;
  readonly 'direction-row': string;
  readonly 'direction-column': string;
  readonly 'align-start': string;
  readonly 'align-center': string;
  readonly 'align-end': string;
  readonly 'align-stretch': string;
  readonly 'align-baseline': string;
  readonly 'justify-start': string;
  readonly 'justify-center': string;
  readonly 'justify-end': string;
  readonly 'justify-between': string;
  readonly 'justify-around': string;
  readonly 'justify-evenly': string;
  readonly 'wrap-nowrap': string;
  readonly 'wrap-wrap': string;
  readonly 'wrap-wrap-reverse': string;
};
export default styles;
