name: 'Comment on PR'
description: 'Find or create a comment on a PR with a unique marker'
inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  comment-marker:
    description: 'Unique marker to identify this comment'
    required: true
  comment-body:
    description: 'Body of the comment to post'
    required: true
outputs:
  comment-id:
    description: 'ID of the created or updated comment'
    value: ${{ steps.comment.outputs.comment-id }}
runs:
  using: 'composite'
  steps:
    - name: Find or create comment
      id: comment
      uses: actions/github-script@v8
      env:
        COMMENT_MARKER: ${{ inputs.comment-marker }}
        COMMENT_BODY: ${{ inputs.comment-body }}
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const marker = process.env.COMMENT_MARKER;
          const body = process.env.COMMENT_BODY;

          // Find existing comment with marker
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });

          const existingComment = comments.find(comment => 
            comment.body?.includes(marker)
          );

          if (existingComment) {
            // Update existing comment
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: existingComment.id,
              body: body,
            });
            core.setOutput('comment-id', existingComment.id);
          } else {
            // Create new comment
            const { data: comment } = await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: body,
            });
            core.setOutput('comment-id', comment.id);
          }
