declare const styles: {
  readonly container: string;
  readonly fullWidth: string;
  readonly label: string;
  readonly required: string;
  readonly inputWrapper: string;
  readonly input: string;
  readonly sizeSmall: string;
  readonly sizeMedium: string;
  readonly sizeLarge: string;
  readonly variantOutlined: string;
  readonly variantFilled: string;
  readonly error: string;
  readonly disabled: string;
  readonly hasStartAdornment: string;
  readonly hasEndAdornment: string;
  readonly startAdornment: string;
  readonly endAdornment: string;
  readonly helperText: string;
  readonly errorText: string;
};
export default styles;
