name: Dependency:Report Outdated

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 2" # Perform every Tuesday at midnight

permissions:
  contents: write
  actions: none
  checks: none
  deployments: none
  issues: none
  packages: read
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Generate Outdated Dependencies Report
        uses: ./.github/actions/dependency-outdated-report
        with:
          PAT_DEPENDENCY_CHECK_UPDATE: ${{ secrets.PAT_DEPENDENCY_CHECK_UPDATE }}
          SETUP_VERSION_FILE: ".tool-versions"
