name: Dependency - Update Dependencies

on:
  schedule:
    - cron: "0 0 * * 1" # Run every Monday at midnight
  workflow_dispatch:

permissions:
  contents: write
  actions: none
  checks: none
  deployments: none
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_DEPENDENCY_CHECK_UPDATE }}

      - name: Update .npmrc with authentication token
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.PAT_DEPENDENCY_CHECK_UPDATE }}" > ~/.npmrc

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Update dependencies (minor and patch versions only)
        run: pnpm update -r

      - name: Update outdated dependencies report
        run: pnpm exec node .github/scripts/generateOutdatedReport.js

      - name: Check for changes
        id: check_changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes=true" >> $GITHUB_ENV
          else
            echo "changes=false" >> $GITHUB_ENV
          fi

      - name: Commit and push updates
        if: env.changes == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'chore: update dependencies'
          git push
        env:
          changes: ${{ env.changes }}
