name: Publish Storybook to Production
description: |
  This workflow publishes the Storybook to GitHub Pages for the main branch.
  It is manually triggered.

on:
  workflow_dispatch:

permissions:
  contents: read
  deployments: write
  actions: none
  checks: none
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  publish-storybook-to-prod:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      # Step 3: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23"
          cache: "pnpm"

      # Step 4: Install dependencies
      - name: Install dependencies
        run: pnpm install

      # Step 5: Build Design System
      - name: Build Design System
        run: pnpm build:design-system

      # Step 6: Build Storybook
      - name: Build Storybook
        run: pnpm build:apps:storybook

      # Step 7: Deploy to GitHub Pages
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.STORYBOOK_FTP_URL }}
          port: ${{ secrets.STORYBOOK_FTP_PORT }}
          protocol: ${{ secrets.STORYBOOK_FTP_PROTOCOL }}
          username: ${{ secrets.STORYBOOK_FTP_LOGIN }}
          password: ${{ secrets.STORYBOOK_FTP_PWD }}
          local-dir: ./packages/apps/storybook/storybook-static
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/cgi-bin/**
